# Generated by Django 4.1.1 on 2023-05-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cusBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusCode', models.CharField(max_length=12, unique=True)),
                ('cusName', models.CharField(max_length=100)),
                ('opeBal', models.IntegerField(blank=True, default=0, null=True)),
                ('cloBal', models.IntegerField(blank=True, default=0, null=True)),
                ('cusActive', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cusExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusCode', models.CharField(max_length=12, unique=True)),
                ('cusLogo', models.ImageField(blank=True, null=True, upload_to='images/cusLogo')),
                ('cusPhone', models.CharField(blank=True, max_length=25, null=True)),
                ('cusEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('cusWeb', models.CharField(blank=True, max_length=100, null=True)),
                ('cusBillTo', models.CharField(blank=True, max_length=100, null=True)),
                ('cusShipTo', models.CharField(blank=True, max_length=100, null=True)),
                ('cusAcNum', models.CharField(blank=True, max_length=50, null=True)),
                ('cusCrLim', models.IntegerField(blank=True, default=0, null=True)),
                ('cusPytTerm', models.CharField(blank=True, max_length=100, null=True)),
                ('cusBank', models.CharField(blank=True, max_length=100, null=True)),
                ('cusLegName', models.CharField(blank=True, max_length=100, null=True)),
                ('cusTRN', models.CharField(blank=True, max_length=25, null=True)),
                ('cusTP', models.CharField(blank=True, max_length=50, null=True)),
                ('cusTOJ', models.CharField(blank=True, max_length=50, null=True)),
                ('cusCP', models.CharField(blank=True, max_length=50, null=True)),
                ('cusCPN', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='qotAddi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qotRef', models.CharField(max_length=14)),
                ('sno', models.CharField(max_length=12)),
                ('itmCode', models.CharField(max_length=12)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.FloatField(blank=True, default=0, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('disc', models.FloatField(blank=True, default=0, null=True)),
                ('tot', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='qotBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qotRef', models.CharField(max_length=14, unique=True)),
                ('qotDat', models.DateField(blank=True, null=True)),
                ('cusCode', models.CharField(blank=True, max_length=20, null=True)),
                ('cusName', models.CharField(max_length=100, null=True)),
                ('qotTBD', models.FloatField(blank=True, default=0, null=True)),
                ('qotTAD', models.FloatField(blank=True, default=0, null=True)),
                ('qotTax', models.FloatField(blank=True, default=0, null=True)),
                ('qotTAT', models.FloatField(blank=True, default=0, null=True)),
                ('shipTo', models.CharField(blank=True, max_length=100, null=True)),
                ('qotComm', models.CharField(blank=True, max_length=200, null=True)),
                ('salPer', models.CharField(blank=True, max_length=10, null=True)),
                ('spName', models.CharField(blank=True, max_length=100, null=True)),
                ('opnClo', models.CharField(blank=True, default='Open', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='soAddi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soRef', models.CharField(max_length=14)),
                ('sno', models.CharField(max_length=12)),
                ('itmCode', models.CharField(max_length=12)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.FloatField(blank=True, default=0, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('disc', models.FloatField(blank=True, default=0, null=True)),
                ('tot', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='soBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soRef', models.CharField(max_length=14, unique=True)),
                ('soDat', models.DateField(blank=True, null=True)),
                ('cusCode', models.CharField(blank=True, max_length=20, null=True)),
                ('cusName', models.CharField(max_length=100, null=True)),
                ('soTBD', models.FloatField(blank=True, default=0, null=True)),
                ('soTAD', models.FloatField(blank=True, default=0, null=True)),
                ('soTax', models.FloatField(blank=True, default=0, null=True)),
                ('soTAT', models.FloatField(blank=True, default=0, null=True)),
                ('shipTo', models.CharField(blank=True, max_length=100, null=True)),
                ('soComm', models.CharField(blank=True, max_length=200, null=True)),
                ('opnClo', models.CharField(blank=True, default='Open', max_length=10, null=True)),
                ('spName', models.CharField(blank=True, max_length=100, null=True)),
                ('spCode', models.CharField(blank=True, max_length=10, null=True)),
                ('qotRef', models.CharField(max_length=14)),
                ('qotDat', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='soaddi',
            index=models.Index(fields=['soRef'], name='F1_Sales_so_soRef_71c045_idx'),
        ),
        migrations.AddIndex(
            model_name='qotaddi',
            index=models.Index(fields=['qotRef'], name='F1_Sales_qo_qotRef_00366c_idx'),
        ),
    ]
