# Generated by Django 4.1.1 on 2023-05-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F1_Sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dlAddi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlRef', models.CharField(max_length=14)),
                ('sno', models.CharField(max_length=12)),
                ('itmCode', models.CharField(max_length=12)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.FloatField(blank=True, default=0, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('disc', models.FloatField(blank=True, default=0, null=True)),
                ('tot', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='dlBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlRef', models.CharField(max_length=14, unique=True)),
                ('dlDat', models.DateField(blank=True, null=True)),
                ('cusCode', models.CharField(blank=True, max_length=20, null=True)),
                ('cusName', models.CharField(max_length=100, null=True)),
                ('dlTBD', models.FloatField(blank=True, default=0, null=True)),
                ('dlTAD', models.FloatField(blank=True, default=0, null=True)),
                ('dlTax', models.FloatField(blank=True, default=0, null=True)),
                ('dlTAT', models.FloatField(blank=True, default=0, null=True)),
                ('shipTo', models.CharField(blank=True, max_length=100, null=True)),
                ('dlComm', models.CharField(blank=True, max_length=200, null=True)),
                ('opnClo', models.CharField(blank=True, default='Open', max_length=10, null=True)),
                ('spName', models.CharField(blank=True, max_length=100, null=True)),
                ('spCode', models.CharField(blank=True, max_length=10, null=True)),
                ('soRef', models.CharField(max_length=14)),
                ('soDat', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='dladdi',
            index=models.Index(fields=['dlRef'], name='F1_Sales_dl_dlRef_fa8963_idx'),
        ),
    ]
