# Generated by Django 4.1.1 on 2023-05-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('F1_Sales', '0002_dladdi_dlbasic_dladdi_f1_sales_dl_dlref_fa8963_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='siAddi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siRef', models.CharField(max_length=14)),
                ('sno', models.CharField(max_length=12)),
                ('itmCode', models.CharField(max_length=12)),
                ('desc', models.CharField(blank=True, max_length=200, null=True)),
                ('qty', models.FloatField(blank=True, default=0, null=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('disc', models.FloatField(blank=True, default=0, null=True)),
                ('tot', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='siBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siRef', models.CharField(max_length=14, unique=True)),
                ('siDat', models.DateField(blank=True, null=True)),
                ('cusCode', models.CharField(blank=True, max_length=20, null=True)),
                ('cusName', models.CharField(max_length=100, null=True)),
                ('siTBD', models.FloatField(blank=True, default=0, null=True)),
                ('siTAD', models.FloatField(blank=True, default=0, null=True)),
                ('siTax', models.FloatField(blank=True, default=0, null=True)),
                ('siTAT', models.FloatField(blank=True, default=0, null=True)),
                ('shipTo', models.CharField(blank=True, max_length=100, null=True)),
                ('siComm', models.CharField(blank=True, max_length=200, null=True)),
                ('opnClo', models.CharField(blank=True, default='Open', max_length=10, null=True)),
                ('spName', models.CharField(blank=True, max_length=100, null=True)),
                ('spCode', models.CharField(blank=True, max_length=10, null=True)),
                ('dlRef', models.CharField(max_length=14)),
                ('dlDat', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='siaddi',
            index=models.Index(fields=['siRef'], name='F1_Sales_si_siRef_0d7475_idx'),
        ),
    ]
