# Generated by Django 4.1.7 on 2023-03-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stdGrouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1', models.CharField(max_length=30, unique=True)),
                ('level2', models.CharField(max_length=30, unique=True)),
                ('level3', models.CharField(max_length=60, unique=True)),
                ('level4', models.CharField(max_length=60, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('head', models.CharField(max_length=200)),
            ],
        ),
    ]
