# Generated by Django 4.1.7 on 2023-03-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_Setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdgrouping',
            name='level1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='stdgrouping',
            name='level2',
            field=models.CharField(max_length=30),
        ),
    ]
