# Generated by Django 4.1.7 on 2023-03-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_Setup', '0002_alter_stdgrouping_level1_alter_stdgrouping_level2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stdgrouping',
            name='level3',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='stdgrouping',
            name='level4',
            field=models.CharField(max_length=60),
        ),
    ]
