# Generated by Django 4.1.1 on 2023-04-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='triBal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('head', models.CharField(max_length=200)),
                ('level1', models.CharField(max_length=50)),
                ('level2', models.CharField(max_length=50)),
                ('level3', models.CharField(max_length=80)),
                ('level4', models.CharField(max_length=80)),
                ('opening', models.FloatField(blank=True, default=0, null=True)),
                ('debit', models.FloatField(blank=True, default=0, null=True)),
                ('credit', models.FloatField(blank=True, default=0, null=True)),
                ('closing', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
