# Generated by Django 4.1.1 on 2023-04-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empCode', models.CharField(max_length=12, unique=True)),
                ('empFName', models.CharField(max_length=20)),
                ('empMName', models.CharField(max_length=20)),
                ('empLName', models.CharField(max_length=20)),
                ('empStat', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='empExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empCode', models.CharField(max_length=12, unique=True)),
                ('empImg', models.ImageField(blank=True, null=True, upload_to='images/empImg')),
                ('empPosi', models.CharField(blank=True, max_length=60, null=True)),
                ('empDoj', models.DateField(blank=True, null=True)),
                ('empEid', models.CharField(blank=True, max_length=30, null=True)),
                ('empLoca', models.CharField(blank=True, max_length=40, null=True)),
                ('empDept', models.CharField(blank=True, max_length=40, null=True)),
                ('empRepTo', models.CharField(blank=True, max_length=30, null=True)),
                ('Sponsor', models.CharField(blank=True, max_length=60, null=True)),
                ('empNatl', models.CharField(blank=True, max_length=20, null=True)),
                ('empGend', models.CharField(blank=True, max_length=10, null=True)),
                ('empDob', models.DateField(blank=True, null=True)),
                ('EmpMarr', models.CharField(blank=True, max_length=10, null=True)),
                ('empIban', models.CharField(blank=True, max_length=30, null=True)),
                ('empBank', models.CharField(blank=True, max_length=20, null=True)),
                ('empAcc', models.CharField(blank=True, max_length=20, null=True)),
                ('empUid', models.CharField(blank=True, max_length=20, null=True)),
                ('empVisa', models.CharField(blank=True, max_length=20, null=True)),
                ('empAdd', models.CharField(blank=True, max_length=50, null=True)),
                ('empPh', models.CharField(blank=True, max_length=20, null=True)),
                ('empEmail', models.CharField(blank=True, max_length=30, null=True)),
                ('ref', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
