# Generated by Django 4.1.1 on 2023-04-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I1_Hrm', '0002_alter_empextra_empbank_alter_empextra_empemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empextra',
            old_name='Sponsor',
            new_name='empSpon',
        ),
        migrations.AlterField(
            model_name='empextra',
            name='empDob',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='empextra',
            name='empDoj',
            field=models.DateField(blank=True, default='2000-01-01', null=True),
        ),
    ]
