# Generated by Django 4.1.1 on 2023-05-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('I1_Hrm', '0003_rename_sponsor_empextra_empspon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empbasic',
            name='empMName',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
