# Generated by Django 4.1.1 on 2023-05-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1_Items', '0002_alter_itmextra_itmlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='itmLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itmCode', models.CharField(max_length=12, unique=True)),
                ('itmName', models.CharField(max_length=100)),
                ('traDat', models.DateField(blank=True, null=True)),
                ('qtyPU', models.IntegerField(blank=True, default=0, null=True)),
                ('costPU', models.IntegerField(blank=True, default=0, null=True)),
                ('qtyTOT', models.IntegerField(blank=True, default=0, null=True)),
                ('costTOT', models.IntegerField(blank=True, default=0, null=True)),
                ('WAC', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
