# Generated by Django 4.1.1 on 2023-05-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1_Items', '0003_itmledger'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='itmledger',
            index=models.Index(fields=['itmCode'], name='H1_Items_it_itmCode_5e8a0a_idx'),
        ),
    ]
