# Generated by Django 4.1.1 on 2023-05-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1_Items', '0004_itmledger_h1_items_it_itmcode_5e8a0a_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itmledger',
            name='itmCode',
            field=models.CharField(max_length=12),
        ),
    ]
