# Generated by Django 4.1.1 on 2023-05-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1_Items', '0005_alter_itmledger_itmcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='itmledger',
            name='desc',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
