# Generated by Django 4.1.1 on 2023-04-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supCode', models.CharField(max_length=12, unique=True)),
                ('supName', models.CharField(max_length=100)),
                ('opeBal', models.IntegerField(blank=True, default=0, null=True)),
                ('cloBal', models.IntegerField(blank=True, default=0, null=True)),
                ('supActive', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='supExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supCode', models.CharField(max_length=12, unique=True)),
                ('supLogo', models.ImageField(blank=True, null=True, upload_to='images/supLogo')),
                ('supPhone', models.CharField(blank=True, max_length=25, null=True)),
                ('supEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('supWeb', models.CharField(blank=True, max_length=100, null=True)),
                ('supBillFrom', models.CharField(blank=True, max_length=100, null=True)),
                ('supShipFrom', models.CharField(blank=True, max_length=100, null=True)),
                ('supAcNum', models.CharField(blank=True, max_length=50, null=True)),
                ('supCrLim', models.IntegerField(blank=True, default=0, null=True)),
                ('supPytTerm', models.CharField(blank=True, max_length=100, null=True)),
                ('supBank', models.CharField(blank=True, max_length=100, null=True)),
                ('supLegName', models.CharField(blank=True, max_length=100, null=True)),
                ('supTRN', models.CharField(blank=True, max_length=25, null=True)),
                ('supTP', models.CharField(blank=True, max_length=50, null=True)),
                ('supTOJ', models.CharField(blank=True, max_length=50, null=True)),
                ('supCP', models.CharField(blank=True, max_length=50, null=True)),
                ('supCPN', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
